### ISSUE TITLE
Problems when installing/launching.  Can't get most things to work.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#1]
$ npx x3d-tidy -i StandardHumanoidNoSegSite.x3d -o StandardHumanoidNoSegSite.x3dv
Need to install the following packages:
  x3d-tidy@1.0.47
Ok to proceed? (y) y
spawn electron ENOENT

**Comment by create3000** [comment]
Guess you are using Windows.

**Comment by coderextreme** [comment]
Yes, I am using Windows 10.

**Comment by coderextreme** [comment]
I'm looking for a command I can run from ant.  No pipe or redirects are allowed that I know of.  Let me google.

**Comment by create3000** [comment]
Did it create the output file?

**Comment by create3000** [comment]
What happens if you do `npx x3d-tidy -h`. It should print a help page.

**Comment by coderextreme** [comment]
```bash
$ npx x3d-tidy -h
spawn electron ENOENT
```

**Comment by coderextreme** [comment]
I decided to use a perl script in my build file instead of trying to run a shell.  the perl system function came in handy!

If we get x3d-tidy working, I can add it to the perl script.

**Comment by create3000** [comment]
Fixed run on Windows. Please have another try. Guess you node version is up to date.

**Comment by create3000** [comment]
I think I finally got it. x3d-tidy v1.0.53 should do it.

**Comment by create3000** [comment]
You should normally not want to uninstall it. The program is in the npm / npx cache.

**Comment by coderextreme** [comment]
$ npx x3d-tidy@1.0.56 -i ./flowers2.x3d -o ./flowers2.x3dj
Need to install the following packages:
  x3d-tidy@1.0.56
Ok to proceed? (y) Y


$ ls !$
ls ./flowers2.x3dj
ls: cannot access './flowers2.x3dj': No such file or directory

**Comment by coderextreme** [comment]
$ npx x3d-tidy -i abox.x3d -o abox.x3dv
Need to install the following packages:
  x3d-tidy@1.0.56
Ok to proceed? (y) y

$ ls abox.x3dv
ls: cannot access 'abox.x3dv': No such file or directory

**Comment by coderextreme** [comment]
Here's a clue:

$ npx x3d-tidy -i ../data/abox.x3d -o ../data/abox.x3dv

ENOENT: no such file or directory, open 'C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\data\abox.x3dv'
