### ISSUE TITLE
Relative paths don't work?

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#10]
npx x3d-tidy -i lily_73/lily_73.x3d -o  lily_73/lily_73.x3dsource.x3dv

ENOENT: no such file or directory, open 'C:\Users\john\AppData\Local\npm-cache\_npx\e9b6d5b508ffea3a\node_modules\x3d-tidy\lily_73\lily_73.x3dsource.x3dv'

This works, AFAICT right now:

npx x3d-tidy -i /c/Users/john/Tufani/HAnimDecoratorAssembly/lily_73/lily_73.x3d -o  /c/Users/john/Tufani/HAnimDecoratorAssembly/lily_73/lily_73.x3dsource.x3dv

John

**Comment by coderextreme** [comment]
If you recommend, I can remove my cache for x3d-tidy.

Thanks,

coderextreme

**Comment by coderextreme** [comment]
Something like this may work:

let data = fs.readFileSync(__dirname + '/InputDir73/7_3_WEIGHTS.txt').toString();

In node.js

**Comment by coderextreme** [comment]
normally, when using x3d-tidy, I use `pwd`/foo.x3d for files.  Works, so should __dirname in node.js

**Comment by create3000** [comment]
I cannot reproduce this. Have again tested on Window and it works as expected.

Yes, do `npx clear-npx-cache`, and then please try again.

**Comment by coderextreme** [comment]
npx x3d-tidy -i
/c/Users/john/Tufani/HAnimDecoratorAssembly/lily_73/lily_73.x3d -o
/c/Users/john/Tufani/HAnimDecoratorAssembly/lily_73/lily_73.x3dsource.x3dv
Need to install the following packages:
  ***@***.***
Ok to proceed? (y) y

(seems to work, lets try without full path)

Also tested with relative paths.  Works. I hope it doesn't break anymore!

John
