### ISSUE TITLE
Cute trick for folders with spaces.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#13]
npx x3d-tidy -i "\`pwd\`"/gramps_anim_short.gltf -o "\`pwd\`"/gramps_anim_short.x3dv

I haven't tried relative paths recently.

**Comment by create3000** [comment]
I don't see that there is a problem with spaces in the file name. 
I testet this command: `npx x3d-tidy -i foo\ bah/empty.x3dv -o .x3d`.

**Comment by coderextreme** [comment]
Try something like ‘pwd’/myfile.x3d (i can’t do backtics on my phone).

Double quotes are required around ‘pwd’ to escape spaces.

Easy shortcut to avoid typing in entire folder.

This is on git for windows.  I don’t know about mac and linux.

John
