### ISSUE TITLE
Possible issue with moving IS to bottom of Transform children.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#14]
$ npx x3d-tidy -i `pwd`/BoxEm.x3d -o `pwd`/BoxEm.x3dj

The result .x3dj does not pass XML schema when converted to XML with X3DJSONLD.java. The IS statement is moved to bottom of Transform children improperly by x3d-tidy in BoxEm.x3dj.  See BoxEm.x3dj in attached zip.

XML schema is up to date with Source Forge.
[BoxEm.zip](https://github.com/create3000/x3d-tidy/files/13676734/BoxEm.zip)

I do not know if XML schema is wrong or x3d-tidy is wrong.

**Comment by create3000** [comment]
As it turns out, there is not an intrinsic order of properties in a JSON schema object.

See also https://stackoverflow.com/questions/31691247/how-can-i-define-the-sequence-of-properties-in-json-schema/31693656#31693656.

**Comment by coderextreme** [comment]
Understood, but I am translating JSON to XML/DOM with X3DJSONLD, and then I
am validating the XML/DOM with XML Schema, which does have extrinsic
order.  Since JSON schema may never be standardized, we may be dependent on
XML Schema for JSON validation.

I fully realize that my X3DJSONLD should “do the right thing” and reorder
the children, but also realize that my X3DJSONLD also has an installed base.

We don’t want to “break the web” if we don’t have to.

I realize that x3d-tidy already repairs these things when converting JSON
back to XML, and I will likely look at the source to see what has been
done, I am kind of curious at this point.  I will probably have to examine
XML Schema and X3DUOM to find these specialized orderings.  I am pretty
sure they are not in X3DUOM, since I’ve had a lot of experience with X3DUOM.

The solution is probably to fix both X3DJSOLD and x3d-tidy.

cc:ed to x3d-public as FYI

John

**Comment by coderextreme** [comment]
See differences between these two files, disappearance of some fieldValue (search for @value) in Holger version, reordering of ProtoDeclare (I think this may be okay for VRML, not sure.  I'm going to test the XML output from X3DJSONLD.java based XML Schema validation soon).  [x3dconnectorProto.json](https://github.com/create3000/x3d-tidy/files/13797759/x3dconnectorProto.json)
[holgerProto.json](https://github.com/create3000/x3d-tidy/files/13797760/holgerProto.json)
