### ISSUE TITLE
x3d-tidy producing -1 radius for SpotLight in .x3dj file

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#18]
Ajv reports (in ~/glTF-Sample-Models/2.0)

location in document: /X3D/Scene/-children/1/Group/-children/1/PointLight/@radius
 params: {"comparison":">=","limit":0}
 file: ./TransmissionSuzanne/glTF/TransmissionSuzanne.x3dj

 location in document: /X3D/Scene/-children/1/Group/-children/3/PointLight/@radius
 params: {"comparison":">=","limit":0}
 file: ./LightsPunctualLamp/glTF/LightsPunctualLamp.x3dj

Code looks like:

```
             { "PointLight":
                {
                  "@DEF": "Light2",
                  "@intensity": 20,
                  "@attenuation": [ 0, 0, 1 ],
                  "@location": [ -1, 0, -2 ],
                  "@radius": -1
                }
```

X3D4 says:

SFFloat [in,out] radius           100   [0,∞)

https://www.web3d.org/specifications/X3Dv4/ISO-IEC19775-1v4-IS/Part01/components/lighting.html#PointLight

negative radii are not allowed.

I'm not sure about glTF.

**Comment by create3000** [comment]
glTF has a default radius of infinity (if nothing is set in the file). This is not possible to set in X3D because the range [0,∞) is exclusive on the right. I use here -1 for infinity.

**Comment by create3000** [comment]
X3DOM uses a value of `1e6` for infinity. Perhaps I should also use a large value.

**Comment by coderextreme** [comment]
I m not sure how JSON Schema handles Infinity, probably just avoids
specifying a mas value.  There is max inclusive and max exclusive.

**Comment by coderextreme** [comment]
Here is recent schema:

https://github.com/coderextreme/x3dvalidate/blob/master/schemas/x3d-4.0-JSONSchema.json

John

**Comment by create3000** [comment]
It is not possible to use a large value or infinity, because glTF uses a separate calculation for infinity light. A value of `-1` seems preferable for infinity.

**Comment by create3000** [comment]
A value of `-1` is a few times used in some nodes. X3DViewpointNode.nearDistance and X3DViewpointNode.farDistance can be `-1` to denote that it should automatically be determined, as well as X3DBoundedObject.bboxSize.

By the way, I also have implemented that X3DEnvironmentalSensorNode.size can be set to (-1 -1 -1) which denotes an infinite size, which is sometimes desired and more save and elegant than using a large value, which is sometimes hard to determine.

**Comment by coderextreme** [comment]
Can you set a minimum inclusive of -1 somewhere?  I’m not sure of syntax.
