### ISSUE TITLE
@specularColor > 1 in SpecularTest.x3dj derived from Khronos' SpecularTest.gltf

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#19]
location in document: /X3D/Scene/-children/1/Group/-children/1/Transform/-children/19/Transform/-children/0/Shape/-appearance/Appearance/-material/PhysicalMaterial/-extensions/0/SpecularMaterialExtension/@specularColor/0
 params: {"comparison":"<=","limit":1}
 file: ./SpecularTest/glTF/SpecularTest.x3dj

This link says:
https://create3000.github.io/x_ite/components/x-ite/specularmaterialextension/

SFColor [in, out] specularColor 1 1 1 [0,1]

Produced JSON .x3dj code looks like (sample):
```
                                        { "SpecularMaterialExtension":
                                          {
                                            "@specularColor": [ 25, 25, 25 ]
                                          }
                                        }
```
(Among others, may references in this code.

glTF comes from:

~/glTF-Sample-Models/2.0/SpecularTest/glTF/SpecularTest.gltf

As converted to .x3dj JSON by x3d-tidy!

There are many @specularColor in the file, but the last 4 are problematic!
```
$ grep @specularColor'"' SpecularTest.x3dj|tail -4
                                            "@specularColor": [ 1.184, 1.184, 1.184 ]
                                            "@specularColor": [ 5.441, 5.441, 5.441 ]
                                            "@specularColor": [ 13.276, 13.276, 13.276 ]
                                            "@specularColor": [ 25, 25, 25 ]
```

Apologies if I don't feel comfortable sharing Khronos IP!

Thanks!

**Comment by create3000** [comment]
In https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md there is a sentence: The specular color factor is allowed to be set to values greater than [1, 1, 1]. To get this working in X3D we must allow color values greater than 1. As far as I know, Castle also allows color values greater than one, to achieve various effects, which would otherwise require a greater effort.

**Comment by coderextreme** [comment]
I believe that it's in the X_ITE SpecularMaterialExtension node.  So if you
update your X3DUOM or preferably your specification for the
SpecularMaterialExtension, I can change the range.  Or I can change my copy
of your X3DUOM extensions to suit my needs, realizing that I may tromp it
at some point.

See attached X_ITE X3DUOM with my changes.  I have a merge program now to
merge your X3DUOM with the main one.  Since this only affects the X_ITE
component, AFAIK, I just am currently working on a good JSON schema so I
can validate the X_ITE component in files converted from .gltf to .x3dj.

Is there an upper bound to the specular color?  Also, it looks like your
use of specularColor has a different name from the Khronos names, which may
be intentional.

It looks like specularColor is also under: SpecularGlossinessMaterial,
which I missed earlier.  Oops!  But it's deprecated on your X_ITE component
website.  I recommend that we move it out of the x3d-tidy .x3dj output, if
possible.

Affected x3d-tidy output files will be:

***@***.*** MINGW64 ~/glTF-Sample-Models (main)
$ find . -type f -print0 | xargs -0 grep -l SpecularGlossinessMaterial
./2.0/SpecGlossVsMetalRough/glTF/SpecGlossVsMetalRough.x3d
./2.0/SpecGlossVsMetalRough/glTF/SpecGlossVsMetalRough.x3dj
./2.0/SpecGlossVsMetalRough/glTF/SpecGlossVsMetalRough.x3dv

So conversion from .gltf will need to be changed.  Perhaps I should just
delete the .gltf.  Hmm!

Thanks for listening!

John

**Comment by create3000** [comment]
Updated X3DUOM and set *maxExclusive* of *specularColor* of SpecularMaterialExtension to Infinity. 

When I release the next version, the X3DUOM in the `dist` folder https://github.com/create3000/x_ite/blob/main/dist/X3DUOM.xml will be updated.

**Comment by coderextreme** [comment]
I think I have your repo checked out as opposed to my fork, so I’ll just do
a gif pull.

Hopefully, you’ve adopted most of the few changes I’ve made.  Probably the
controversial one is moving the component for Tangent (?) from Rendering to
X_ITE.  Please override whatever you feel is best, and I’ll try to adapt .

John

**Comment by create3000** [comment]
I want to try to avoid moving Tangent to X_ITE component, because it is a breaking change. People first get an error, when loading files with Tangent, and must then manually add X_ITE component. This is bad.

**Comment by coderextreme** [comment]
Okay, that’s something for me to change. I don’t think it affects X3D JSON Schema.
