### ISSUE TITLE
unicode characters in JSON?  JSON output from x3d-tidy from converting glTF to X3D JSON

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#20]
.X3DJ:

![image](https://github.com/user-attachments/assets/913b2ecc-5442-455c-8079-348a87eae570)

Present in glTF:

![image](https://github.com/user-attachments/assets/0ca9cf4f-17c8-47c8-aff7-3bc20fb97b1e)

I'm not sure what to do.  Maybe change the url to something which meets W3C/JSONSchema/X3D  standards for URIs

**Comment by create3000** [comment]
Maybe this answer helps: https://stackoverflow.com/a/594881/1818915

**Comment by coderextreme** [comment]
Maybe,  but these look like emojis, I think I've never seen an emoji in a
URI.

Thanks,

John

**Comment by create3000** [comment]
Those emoji in a text are also only uff-8 sequences, and interpreted by the text editor and shown as images.

**Comment by coderextreme** [comment]
I will change X3D JSON schema to allow iri and iri-reference.  Feel free to post an issue.  https://en.m.wikipedia.org/wiki/Internationalized_Resource_Identifier

**Comment by coderextreme** [comment]
x3dvalidate should now support uri-reference, iri-reference, uri and iri formats, courtesy of:

ajv-formats-draft2019:  [ajv-formats-draft2019 - npm](https://www.npmjs.com/package/ajv-formats-draft2019)

Resolved.
