### ISSUE TITLE
Simple x3d-tidy commands with `pwd` not working! On Windows 11, Git 4 Windows Git Bash

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#21]
jcarl@JustHumans MINGW64 ~/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF (main)
$ npx x3d-tidy@latest -i `pwd`/GlamVelvetSofa.gltf -o `pwd`/GlamVelvetSofa.x3d
(node:11704) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1408) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Cannot read properties of undefined (reading 'getExecutionContext')

jcarl@JustHumans MINGW64 ~/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF (main)
$ npx x3d-tidy@latest -i `pwd`/GlamVelvetSofa.gltf -o `pwd`/GlamVelvetSofa.x3dv
(node:12948) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24236) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Cannot read properties of undefined (reading 'getExecutionContext')

jcarl@JustHumans MINGW64 ~/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF (main)
$ npx x3d-tidy@latest -i `pwd`/GlamVelvetSofa.gltf -o `pwd`/GlamVelvetSofa.x3dj
(node:12436) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23252) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Cannot read properties of undefined (reading 'getExecutionContext')

jcarl@JustHumans MINGW64 ~/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF (main)
$ ls -ltr
total 3096
-rw-r--r-- 1 jcarl 197609   17488 Sep  3 08:15 GlamVelvetSofa.gltf
-rw-r--r-- 1 jcarl 197609  124952 Sep  3 08:15 GlamVelvetSofa.bin
-rw-r--r-- 1 jcarl 197609 2487826 Sep  3 08:15 GlamVelvetSofa_normal.png
-rw-r--r-- 1 jcarl 197609  530651 Sep  3 08:15 GlamVelvetSofa_occlusion.png

I'm guessing it has somethiing to do with not being able to get an ExecutionContext?

**Comment by create3000** [comment]
I cannot reproduce this. Maybe a cache problem? Would you please try to use `npx clear-npx-cache` and then  run your command again, and than tell me what happens.

**Comment by coderextreme** [comment]
````
`jcarl@JustHumans MINGW64 ~/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF (main)
$ npx x3d-tidy@latest -i `pwd`/GlamVelvetSofa.gltf -o `pwd`/GlamVelvetSofa.x3d
(node:4432) ExperimentalWarning: CommonJS module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\jcarl\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Need to install the following packages:
x3d-tidy@2.0.6
Ok to proceed? (y) y

npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
(node:19592) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:19592) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:16 Invalid asm.js: Invalid member of stdlib
(node:19592) V8: C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\assets\components\Texturing3DComponent.js:53 Invalid asm.js: Invalid member of stdlib
Couldn't load URL 'c:/Users/jcarl/glTF-Sample-Models/2.0/GlamVelvetSofa/glTF/GlamVelvetSofa.gltf'. TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\node-fetch\lib\index.js:1327:9)
    at C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\node-fetch\lib\index.js:1450:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\node-fetch\lib\index.js:1447:9)
    at value (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite-node\src\index.js:168:23)
    at FileLoader.loadDocumentAsync (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\x_ite.js:67041:48)
    at FileLoader.loadDocument (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\x_ite.js:66967:13)
    at FileLoader.createX3DFromURL (C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\x_ite.js:66950:20)
    at C:\Users\jcarl\AppData\Local\npm-cache\_npx\6afd08d3c48ec865\node_modules\x_ite\dist\x_ite.js:124390:22
    at new Promise (<anonymous>)
Couldn't load X3D file.
```
Note that I'm using Git 4 Windows Git Bash on Windows 11

**Comment by coderextreme** [comment]
Also,  C:\ is linked to /c
```
$ cd C:/

jcarl@JustHumans MINGW64 /c
$
```
