### ISSUE TITLE
Finger? shift of DEF--Creates new DEF for _1 and shifts other DEFs down in number for carpal_proximal_interphalangeal right and left

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#5]
First reported matches are in original file.

$ grep carpal_prox Sibling4d2.x3dv Sibling4d2.Holger.x3d*|cut -c1-130
Sibling4d2.x3dv:        DEF Toddler_l_carpal_proximal_interphalangeal_2 HAnimJoint { name "l_carpal_proximal_interphalangeal_2" ce
Sibling4d2.x3dv:        DEF Toddler_l_carpal_proximal_interphalangeal_3 HAnimJoint { name "l_carpal_proximal_interphalangeal_3" ce
Sibling4d2.x3dv:        DEF Toddler_l_carpal_proximal_interphalangeal_4 HAnimJoint { name "l_carpal_proximal_interphalangeal_4" ce
Sibling4d2.x3dv:        DEF Toddler_l_carpal_proximal_interphalangeal_5 HAnimJoint { name "l_carpal_proximal_interphalangeal_5" ce
Sibling4d2.x3dv:        DEF Toddler_r_carpal_proximal_interphalangeal_2 HAnimJoint { name "r_carpal_proximal_interphalangeal_2" ce
Sibling4d2.x3dv:        DEF Toddler_r_carpal_proximal_interphalangeal_3 HAnimJoint { name "r_carpal_proximal_interphalangeal_3" ce
Sibling4d2.x3dv:        DEF Toddler_r_carpal_proximal_interphalangeal_4 HAnimJoint { name "r_carpal_proximal_interphalangeal_4" ce
Sibling4d2.x3dv:        DEF Toddler_r_carpal_proximal_interphalangeal_5 HAnimJoint { name "r_carpal_proximal_interphalangeal_5" ce
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_l_carpal_proximal_interphalangeal_1'
Sibling4d2.Holger.x3d:                                name='l_carpal_proximal_interphalangeal_2'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_l_carpal_proximal_interphalangeal_2'
Sibling4d2.Holger.x3d:                                name='l_carpal_proximal_interphalangeal_3'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_l_carpal_proximal_interphalangeal_3'
Sibling4d2.Holger.x3d:                                name='l_carpal_proximal_interphalangeal_4'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_l_carpal_proximal_interphalangeal_4'
Sibling4d2.Holger.x3d:                                name='l_carpal_proximal_interphalangeal_5'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_r_carpal_proximal_interphalangeal_1'
Sibling4d2.Holger.x3d:                                name='r_carpal_proximal_interphalangeal_2'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_r_carpal_proximal_interphalangeal_2'
Sibling4d2.Holger.x3d:                                name='r_carpal_proximal_interphalangeal_3'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_r_carpal_proximal_interphalangeal_3'
Sibling4d2.Holger.x3d:                                name='r_carpal_proximal_interphalangeal_4'
Sibling4d2.Holger.x3d:                            <HAnimJoint DEF='Toddler_r_carpal_proximal_interphalangeal_4'
Sibling4d2.Holger.x3d:                                name='r_carpal_proximal_interphalangeal_5'
Sibling4d2.Holger.x3dv:                                  DEF Toddler_l_carpal_proximal_interphalangeal_1 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "l_carpal_proximal_interphalangeal_2"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_l_carpal_proximal_interphalangeal_2 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "l_carpal_proximal_interphalangeal_3"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_l_carpal_proximal_interphalangeal_3 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "l_carpal_proximal_interphalangeal_4"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_l_carpal_proximal_interphalangeal_4 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "l_carpal_proximal_interphalangeal_5"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_r_carpal_proximal_interphalangeal_1 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "r_carpal_proximal_interphalangeal_2"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_r_carpal_proximal_interphalangeal_2 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "r_carpal_proximal_interphalangeal_3"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_r_carpal_proximal_interphalangeal_3 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "r_carpal_proximal_interphalangeal_4"
Sibling4d2.Holger.x3dv:                                  DEF Toddler_r_carpal_proximal_interphalangeal_4 HAnimJoint {
Sibling4d2.Holger.x3dv:                                    name "r_carpal_proximal_interphalangeal_5"

**Comment by create3000** [comment]
The `*_NUMBER` syntax is internally used to handle duplicate names. There should be no disadvantages as a result. This is not a bug, this is a feature.

**Comment by coderextreme** [comment]
X3D-Edit throws lots of issues with the file.

I realize it’s not an issue with rendering.

I don’t think my example uses duplicate names.

John
