### ISSUE TITLE
x3d-tidy .wrl to .x3dj incomplete for HAnim (try LOA4).

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#6]
Items present in .wrl file, but not in .x3dj file or .x3dv file, HAnim.
```
$ npx x3d-tidy -i `pwd`"/InputDir73/lily 7_3_animate.wrl" -o `pwd`/"/InputDir73/lily 7_3_animate.x3dj"
$ egrep 'l_carpal_proximal_interphalangeal_5|l_carpal_distal_interphalangeal_5|r_metatarsophalangeal_2|l_metatarsophalangeal_2|r_carpal_proximal_interphalangeal_5|r_carpal_distal_interphalangeal_5' "InputDir73/lily 7_3_animate.x3dj" "InputDir73/lily 7_3_animate.wrl" |grep -v KEY
[ note: nothing found in JSON file ]
InputDir73/lily 7_3_animate.wrl:                                            DEF r_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF r_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                            DEF l_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF l_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF r_metatarsophalangeal_2 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF l_metatarsophalangeal_2 Transform {
```
Another example works OK:
```
$ npx x3d-tidy -i `pwd`/"OldTemplate.x3dv" -o `pwd`"/OldTemplate.x3dj"
$ egrep 'l_carpal_proximal_interphalangeal_5|l_carpal_distal_interphalangeal_5|r_metatarsophalangeal_2|l_metatarsophalangeal_2|r_carpal_proximal_interphalangeal_5|r_carpal_distal_interphalangeal_5' OldTemplate.x3dv OldTemplate.x3dj
OldTemplate.x3dv:     DEF Toddler_l_metatarsophalangeal_2 HAnimJoint { name "l_metatarsophalangeal_2" center 0.0884 0.0109 0.0439 skinCoordIndex [  ] skinCoordWeight [  ] children [  ]}]}]}]}
OldTemplate.x3dv:     DEF Toddler_r_metatarsophalangeal_2 HAnimJoint { name "r_metatarsophalangeal_2" center -0.0945 0.0107 0.0537 skinCoordIndex [  ] skinCoordWeight [  ] children [  ]}]}]}]}
OldTemplate.x3dv:         DEF Toddler_l_carpal_proximal_interphalangeal_5 HAnimJoint { name "l_carpal_proximal_interphalangeal_5" center 0.329 0.414 -0.008 skinCoordIndex [  ] skinCoordWeight [  ] children [
OldTemplate.x3dv:           DEF Toddler_l_carpal_distal_interphalangeal_5 HAnimJoint { name "l_carpal_distal_interphalangeal_5" center 0.342 0.399 -0.0116 skinCoordIndex [  ] skinCoordWeight [  ] children [  ]}]}]} ]} ]} ]} ]}
OldTemplate.x3dv:         DEF Toddler_r_carpal_proximal_interphalangeal_5 HAnimJoint { name "r_carpal_proximal_interphalangeal_5" center -0.331 0.416 -0.0101 skinCoordIndex [  ] skinCoordWeight [  ] children [
OldTemplate.x3dv:           DEF Toddler_r_carpal_distal_interphalangeal_5 HAnimJoint { name "r_carpal_distal_interphalangeal_5" center -0.343 0.398 -0.0111 skinCoordIndex [  ] skinCoordWeight [  ] children [  ]}]}]} ]} ]} ]} ]}
OldTemplate.x3dj:                                                            "@name": "l_metatarsophalangeal_2",
OldTemplate.x3dj:                                                            "@name": "r_metatarsophalangeal_2",
OldTemplate.x3dj:                                                                                          "@name": "l_carpal_proximal_interphalangeal_5",
OldTemplate.x3dj:                                                                                                      "@name": "l_carpal_distal_interphalangeal_5",
OldTemplate.x3dj:                                                                                          "@name": "r_carpal_proximal_interphalangeal_5",
OldTemplate.x3dj:                                                                                                      "@name": "r_carpal_distal_interphalangeal_5",

```

The file validates against tovrmlx3d:
```
$ ~/Downloads/view3dscene-4.3.0-win64-x86_64/view3dscene/tovrmlx3d.exe --validate  InputDir73/lily\ 7_3_animate.wrl
[ no output ]
```

**Comment by coderextreme** [comment]
Note that XML also does not contain the joints.

**Comment by create3000** [comment]
There is a new fixed version available. Please try this one.

**Comment by coderextreme** [comment]
Well, it seems like I had to force an update:

$ grep -v '#' bad.sh

npx x3d-tidy@1.0.91 -i `pwd`"/InputDir73/lily 7_3_animate.wrl" -o `pwd`"/InputDir73/lily 7_3_animate.x3d"
npx x3d-tidy@1.0.91 -i `pwd`"/InputDir73/lily 7_3_animate.wrl" -o `pwd`"/InputDir73/lily 7_3_animate.x3dj"
egrep 'l_carpal_proximal_interphalangeal_5|l_carpal_distal_interphalangeal_5|r_metatarsophalangeal_2|l_metatarsophalangeal_2|r_carpal_proximal_interphalangeal_5|r_carpal_distal_interphalangeal_5' "InputDir73/lily 7_3_animate.x3dj" "InputDir73/lily 7_3_animate.wrl" "InputDir73/lily 7_3_animate.x3d" | grep -v KEY
$ bash bad.sh


InputDir73/lily 7_3_animate.x3dj:                                                                              "@DEF": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                                    "@DEF": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                              "@DEF": "l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                                    "@DEF": "l_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                "@DEF": "r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:                                                "@DEF": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.wrl:                                            DEF r_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF r_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                            DEF l_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF l_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF r_metatarsophalangeal_2 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF l_metatarsophalangeal_2 Transform {
InputDir73/lily 7_3_animate.x3d:                          <Transform DEF='r_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                            <Transform DEF='r_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                          <Transform DEF='l_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                            <Transform DEF='l_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                <Transform DEF='r_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:                <Transform DEF='l_metatarsophalangeal_2'

**Comment by coderextreme** [comment]
Note that the ROUTE is there, I just filtered it out before with grep -v KEY

$ bash bad.sh


InputDir73/lily 7_3_animate.x3dj:                                                                              "@DEF": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                                    "@DEF": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                              "@DEF": "l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                                                    "@DEF": "l_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:                                                "@DEF": "r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:                                                "@DEF": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "POSKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "ROTKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "POSKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "ROTKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "ROTKEY_l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "ROTKEY_r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "POSKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@DEF": "ROTKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "POSKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "POSKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "ROTKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "ROTKEY_r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "POSKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "POSKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "ROTKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "ROTKEY_r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_carpal_distal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "ROTKEY_l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "ROTKEY_l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_carpal_proximal_interphalangeal_5",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "ROTKEY_r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "ROTKEY_r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "r_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "POSKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "POSKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "ROTKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@fromNode": "ROTKEY_l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.x3dj:            "@toNode": "l_metatarsophalangeal_2",
InputDir73/lily 7_3_animate.wrl:                                            DEF r_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF r_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                            DEF l_carpal_proximal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                                                DEF l_carpal_distal_interphalangeal_5 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF r_metatarsophalangeal_2 Transform {
InputDir73/lily 7_3_animate.wrl:                        DEF l_metatarsophalangeal_2 Transform {
InputDir73/lily 7_3_animate.wrl:DEF POSKEY_r_carpal_proximal_interphalangeal_5 PositionInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO POSKEY_r_carpal_proximal_interphalangeal_5.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE POSKEY_r_carpal_proximal_interphalangeal_5.value_changed TO r_carpal_proximal_interphalangeal_5.set_translation
InputDir73/lily 7_3_animate.wrl:DEF ROTKEY_r_carpal_proximal_interphalangeal_5 OrientationInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO ROTKEY_r_carpal_proximal_interphalangeal_5.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE ROTKEY_r_carpal_proximal_interphalangeal_5.value_changed TO r_carpal_proximal_interphalangeal_5.set_rotation
InputDir73/lily 7_3_animate.wrl:DEF POSKEY_r_carpal_distal_interphalangeal_5 PositionInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO POSKEY_r_carpal_distal_interphalangeal_5.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE POSKEY_r_carpal_distal_interphalangeal_5.value_changed TO r_carpal_distal_interphalangeal_5.set_translation
InputDir73/lily 7_3_animate.wrl:DEF ROTKEY_r_carpal_distal_interphalangeal_5 OrientationInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO ROTKEY_r_carpal_distal_interphalangeal_5.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE ROTKEY_r_carpal_distal_interphalangeal_5.value_changed TO r_carpal_distal_interphalangeal_5.set_rotation
InputDir73/lily 7_3_animate.wrl:DEF ROTKEY_l_carpal_proximal_interphalangeal_5 OrientationInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO ROTKEY_l_carpal_proximal_interphalangeal_5.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE ROTKEY_l_carpal_proximal_interphalangeal_5.value_changed TO l_carpal_proximal_interphalangeal_5.set_rotation
InputDir73/lily 7_3_animate.wrl:DEF ROTKEY_r_metatarsophalangeal_2 OrientationInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO ROTKEY_r_metatarsophalangeal_2.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE ROTKEY_r_metatarsophalangeal_2.value_changed TO r_metatarsophalangeal_2.set_rotation
InputDir73/lily 7_3_animate.wrl:DEF POSKEY_l_metatarsophalangeal_2 PositionInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO POSKEY_l_metatarsophalangeal_2.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE POSKEY_l_metatarsophalangeal_2.value_changed TO l_metatarsophalangeal_2.set_translation
InputDir73/lily 7_3_animate.wrl:DEF ROTKEY_l_metatarsophalangeal_2 OrientationInterpolator {
InputDir73/lily 7_3_animate.wrl:ROUTE Timer.fraction_changed TO ROTKEY_l_metatarsophalangeal_2.set_fraction
InputDir73/lily 7_3_animate.wrl:ROUTE ROTKEY_l_metatarsophalangeal_2.value_changed TO l_metatarsophalangeal_2.set_rotation
InputDir73/lily 7_3_animate.x3d:                          <Transform DEF='r_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                            <Transform DEF='r_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                          <Transform DEF='l_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                            <Transform DEF='l_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:                <Transform DEF='r_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:                <Transform DEF='l_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:    <PositionInterpolator DEF='POSKEY_r_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:    <OrientationInterpolator DEF='ROTKEY_r_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:    <PositionInterpolator DEF='POSKEY_r_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:    <OrientationInterpolator DEF='ROTKEY_r_carpal_distal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:    <OrientationInterpolator DEF='ROTKEY_l_carpal_proximal_interphalangeal_5'
InputDir73/lily 7_3_animate.x3d:    <OrientationInterpolator DEF='ROTKEY_r_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:    <PositionInterpolator DEF='POSKEY_l_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:    <OrientationInterpolator DEF='ROTKEY_l_metatarsophalangeal_2'
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='POSKEY_r_carpal_proximal_interphalangeal_5' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='POSKEY_r_carpal_proximal_interphalangeal_5' fromField='value_changed' toNode='r_carpal_proximal_interphalangeal_5' toField='set_translation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='ROTKEY_r_carpal_proximal_interphalangeal_5' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='ROTKEY_r_carpal_proximal_interphalangeal_5' fromField='value_changed' toNode='r_carpal_proximal_interphalangeal_5' toField='set_rotation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='POSKEY_r_carpal_distal_interphalangeal_5' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='POSKEY_r_carpal_distal_interphalangeal_5' fromField='value_changed' toNode='r_carpal_distal_interphalangeal_5' toField='set_translation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='ROTKEY_r_carpal_distal_interphalangeal_5' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='ROTKEY_r_carpal_distal_interphalangeal_5' fromField='value_changed' toNode='r_carpal_distal_interphalangeal_5' toField='set_rotation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='ROTKEY_l_carpal_proximal_interphalangeal_5' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='ROTKEY_l_carpal_proximal_interphalangeal_5' fromField='value_changed' toNode='l_carpal_proximal_interphalangeal_5' toField='set_rotation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='ROTKEY_r_metatarsophalangeal_2' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='ROTKEY_r_metatarsophalangeal_2' fromField='value_changed' toNode='r_metatarsophalangeal_2' toField='set_rotation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='POSKEY_l_metatarsophalangeal_2' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='POSKEY_l_metatarsophalangeal_2' fromField='value_changed' toNode='l_metatarsophalangeal_2' toField='set_translation'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='Timer' fromField='fraction_changed' toNode='ROTKEY_l_metatarsophalangeal_2' toField='set_fraction'/>
InputDir73/lily 7_3_animate.x3d:    <ROUTE fromNode='ROTKEY_l_metatarsophalangeal_2' fromField='value_changed' toNode='l_metatarsophalangeal_2' toField='set_rotation'/>

**Comment by coderextreme** [comment]
We can have a discussion whether it's @DEF or @def.
